name: Go

on:
  pull_request:
    branches: [ "main", "develop"]

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ '1.14', '1.15', '1.16.x' ]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test with Go
      run: go test -json > TestResults-${{ matrix.go-version }}.json
      
    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
      
    - name: Generate coverage report
      run: |
        go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
